Algoritmo "Questão 03"

var
n1,n2,n3,cont,quadrado:inteiro

Inicio
escreva("digite o primeiro número: ")
leia(n1)

escreva("digite o segundo número: ")
leia(n2)

escreva("digite o terceiro número: ")
leia(n3)

cont<- (n1*100) + (n2*10)+ n3
quadrado<- cont*cont

escreval("a contatenação dos números escolhidos é ",cont)

escreval("o quadrado da contatenação dos números escolhidos é ",quadrado)



Fimalgoritmo